import { jsPDF } from "jspdf";
import type { Conference, Insight } from "@/data/types";

interface ExportOptions {
  conference: Conference;
  tierName: string;
  tierDescription: string;
  insights: Insight[];
}

/** Map common Unicode punctuation/symbols to ASCII so standard PDF fonts render them. */
function ascii(input: string): string {
  return input
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/\u2265/g, ">=")
    .replace(/\u2264/g, "<=")
    .replace(/\u2022/g, "-")
    .replace(/\u00b7/g, "-")
    .replace(/[^\x00-\x7F]/g, "");
}

/**
 * Generates and downloads an executive summary PDF for the selected conference.
 * Every claim carries page-level source attribution (quote, page, confidence).
 */
export function exportExecutiveSummaryPdf({
  conference,
  tierName,
  tierDescription,
  insights,
}: ExportOptions) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginX = 48;
  const contentWidth = pageWidth - marginX * 2;
  let y = 56;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageHeight - 56) {
      doc.addPage();
      y = 56;
    }
  };

  // ---- Header band ----
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 96, "F");
  doc.setTextColor(148, 163, 184); // slate-400
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("VERA 2.0 · EXECUTIVE SUMMARY", marginX, 38);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.text(conference.acronym, marginX, 62);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(203, 213, 225);
  doc.text(
    ascii(`${conference.name} - ${conference.location}`),
    marginX,
    80,
  );
  y = 128;

  // ---- Meta line ----
  doc.setTextColor(71, 85, 105);
  doc.setFontSize(9);
  const dateRange = `${conference.startDate} – ${conference.endDate}`;
  doc.text(
    `${tierName}   |   ${dateRange}   |   Generated ${new Date().toLocaleDateString()}`,
    marginX,
    y,
  );
  y += 14;
  doc.setDrawColor(226, 232, 240);
  doc.line(marginX, y, pageWidth - marginX, y);
  y += 24;

  // ---- Intro ----
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(10);
  const introLines = doc.splitTextToSize(tierDescription, contentWidth);
  doc.text(introLines, marginX, y);
  y += introLines.length * 13 + 16;

  // ---- Insights ----
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  ensureSpace(24);
  doc.text("Key Insights", marginX, y);
  y += 20;

  if (insights.length === 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text("No insights are available for this conference yet.", marginX, y);
    y += 16;
  }

  insights.forEach((insight, idx) => {
    const bodyLines = doc.splitTextToSize(ascii(insight.text), contentWidth - 24);
    const attribution = `Source: "${ascii(insight.sourceQuote)}" - p.${insight.page} | confidence ${insight.confidence}/10`;
    const attrLines = doc.splitTextToSize(attribution, contentWidth - 24);
    const blockHeight = bodyLines.length * 13 + attrLines.length * 11 + 22;
    ensureSpace(blockHeight);

    // number badge
    doc.setFillColor(37, 99, 235);
    doc.circle(marginX + 8, y - 3, 9, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text(String(idx + 1), marginX + 8, y, { align: "center" });

    // body
    doc.setTextColor(30, 41, 59);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(bodyLines, marginX + 24, y);
    y += bodyLines.length * 13 + 4;

    // attribution
    doc.setTextColor(100, 116, 139);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.text(attrLines, marginX + 24, y);
    y += attrLines.length * 11 + 14;
  });

  // ---- Footer on every page ----
  const pageCount = doc.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setDrawColor(226, 232, 240);
    doc.line(marginX, pageHeight - 40, pageWidth - marginX, pageHeight - 40);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      "Generated by VERA — every claim carries direct-extraction source attribution.",
      marginX,
      pageHeight - 26,
    );
    doc.text(`Page ${p} of ${pageCount}`, pageWidth - marginX, pageHeight - 26, {
      align: "right",
    });
  }

  const safeName = conference.acronym.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  doc.save(`${safeName}-executive-summary.pdf`);
}
