import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import { PageHeader, StubNotice } from "@/components/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useInsights } from "@/lib/hooks";
import { useApp } from "@/context/app-context";
import { ExtractionMark } from "@/components/attribution";
import { exportExecutiveSummaryPdf } from "@/lib/export-pdf";
import { Clock, FileText, FileType2, Presentation, Check, Download } from "lucide-react";

export const Route = createFileRoute("/post/deliverables")({
  head: () => ({ meta: [{ title: "Deliverable Generator — VERA 2.0" }] }),
  component: Deliverables,
});

const tiers = [
  {
    id: "exec-1",
    name: "Tier 1 · Headline",
    desc: "5 top-line takeaways for leadership",
    bullets: 3,
  },
  {
    id: "exec-2",
    name: "Tier 2 · Executive Summary",
    desc: "Structured summary by KIT with key data",
    bullets: 4,
  },
  {
    id: "exec-3",
    name: "Tier 3 · Full Conference Report",
    desc: "Complete report with all endpoints & attribution",
    bullets: 5,
  },
];

function Deliverables() {
  const { data: insights = [] } = useInsights();
  const { conference } = useApp();
  const [tier, setTier] = useState("exec-2");
  const selected = tiers.find((t) => t.id === tier)!;
  const preview = insights.filter((i) => !i.duplicateOf).slice(0, selected.bullets);

  const handleExportPdf = () => {
    exportExecutiveSummaryPdf({
      conference,
      tierName: selected.name,
      tierDescription: selected.desc,
      insights: preview,
    });
    toast.success(`Downloaded ${selected.name} PDF for ${conference.acronym}`);
  };

  return (
    <div className="mx-auto max-w-4xl">
      <PageHeader
        eyebrow="Module C · Post-Conference"
        title="Deliverable Generator"
        description="Three tiers of executive summary and a full report, exportable to Word, PowerPoint, and PDF — with full source attribution on every claim."
        actions={
          <Button size="sm" onClick={handleExportPdf}>
            <Download className="h-4 w-4" /> Download PDF summary
          </Button>
        }
      />
      <StubNotice>
        Word and PowerPoint export are simulated. PDF export generates a real,
        downloadable executive summary with source attribution.
      </StubNotice>

      <div className="mb-4 grid gap-3 md:grid-cols-3">
        {tiers.map((t) => (
          <button
            key={t.id}
            onClick={() => setTier(t.id)}
            className={`rounded-xl border p-4 text-left transition-colors ${
              tier === t.id
                ? "border-primary bg-primary/5 ring-1 ring-primary/30"
                : "hover:bg-muted/50"
            }`}
          >
            <div className="mb-1 flex items-center justify-between">
              <span className="text-sm font-semibold">{t.name}</span>
              {tier === t.id && <Check className="h-4 w-4 text-primary" />}
            </div>
            <p className="text-xs text-muted-foreground">{t.desc}</p>
          </button>
        ))}
      </div>

      <Card>
        <CardHeader className="flex-row items-center justify-between space-y-0 pb-3">
          <CardTitle className="text-base">{selected.name} — preview</CardTitle>
          <div className="flex gap-2">
            {[
              { label: "Word", icon: FileText },
              { label: "PowerPoint", icon: Presentation },
            ].map((f) => (
              <Button
                key={f.label}
                size="sm"
                variant="secondary"
                onClick={() => toast.success(`Exported ${selected.name} to ${f.label}`)}
              >
                <f.icon className="h-4 w-4" /> {f.label}
              </Button>
            ))}
            <Button size="sm" onClick={handleExportPdf}>
              <FileType2 className="h-4 w-4" /> PDF
            </Button>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="rounded-lg border bg-card p-5">
            <h3 className="font-display text-lg font-semibold">
              Key Conference Insights — {conference.acronym}
            </h3>
            <p className="mb-4 text-xs text-muted-foreground">
              Generated by VERA · every claim carries source attribution
            </p>
            <ol className="space-y-3">
              {preview.map((i, idx) => (
                <li key={i.id} className="text-sm">
                  <div className="flex gap-2">
                    <span className="font-semibold text-primary">{idx + 1}.</span>
                    <div>
                      <p>{i.text}</p>
                      <p className="mt-1 text-xs text-muted-foreground">
                        <sup>[{idx + 1}]</sup> Source: “{i.sourceQuote}” — p.{i.page},
                        confidence {i.confidence}/10
                      </p>
                    </div>
                  </div>
                </li>
              ))}
            </ol>
          </div>
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            <ExtractionMark /> All numeric claims are direct extractions with page-level
            attribution.
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
