/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrePlannerRouteImport } from './routes/pre.planner'
import { Route as PreLbaRouteImport } from './routes/pre.lba'
import { Route as PreExtractionRouteImport } from './routes/pre.extraction'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrePlannerRoute = PrePlannerRouteImport.update({
  id: '/pre/planner',
  path: '/pre/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const PreLbaRoute = PreLbaRouteImport.update({
  id: '/pre/lba',
  path: '/pre/lba',
  getParentRoute: () => rootRouteImport,
} as any)
const PreExtractionRoute = PreExtractionRouteImport.update({
  id: '/pre/extraction',
  path: '/pre/extraction',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pre/extraction': typeof PreExtractionRoute
  '/pre/lba': typeof PreLbaRoute
  '/pre/planner': typeof PrePlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pre/extraction': typeof PreExtractionRoute
  '/pre/lba': typeof PreLbaRoute
  '/pre/planner': typeof PrePlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pre/extraction': typeof PreExtractionRoute
  '/pre/lba': typeof PreLbaRoute
  '/pre/planner': typeof PrePlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/pre/extraction'
    | '/pre/lba'
    | '/pre/planner'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/pre/extraction' | '/pre/lba' | '/pre/planner'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/pre/extraction'
    | '/pre/lba'
    | '/pre/planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  PreExtractionRoute: typeof PreExtractionRoute
  PreLbaRoute: typeof PreLbaRoute
  PrePlannerRoute: typeof PrePlannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre/planner': {
      id: '/pre/planner'
      path: '/pre/planner'
      fullPath: '/pre/planner'
      preLoaderRoute: typeof PrePlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre/lba': {
      id: '/pre/lba'
      path: '/pre/lba'
      fullPath: '/pre/lba'
      preLoaderRoute: typeof PreLbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre/extraction': {
      id: '/pre/extraction'
      path: '/pre/extraction'
      fullPath: '/pre/extraction'
      preLoaderRoute: typeof PreExtractionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  PreExtractionRoute: PreExtractionRoute,
  PreLbaRoute: PreLbaRoute,
  PrePlannerRoute: PrePlannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
